services:
  graphhopper:
    build: graphHopper/Dockerfile.graphHopper
    image: my-graphhopper:latest
    container_name: graphhopper
    ports:
      - "28989:8989"
    restart: always

  bike-backend:
    build: Dockerfile.backend
    image: bike-backend:latest
    container_name: bike-backend
    restart: always
    ports:
      - "28000:8000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - graphhopper